# Generated by Django 5.0.1 on 2024-03-09 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productCategory', models.CharField(max_length=100)),
                ('productBrand', models.CharField(max_length=100)),
                ('productDescription', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productStock', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/inventory/productImage')),
                ('addProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.addproduct')),
            ],
        ),
    ]
