# Generated by Django 5.0.1 on 2024-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='productCategory',
            field=models.CharField(choices=[('Haircare', 'Haircare'), ('Skincare', 'Skincare'), ('Nail Care', 'Nail Care'), ('Makeup', 'Makeup'), ('Fragrances', 'Fragrances'), ('Tools and Accessories', 'Tools and Accessories')], max_length=100),
        ),
    ]
