# Generated by Django 5.0.1 on 2024-03-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='new_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='new_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
