# Generated by Django 5.0.1 on 2024-04-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_orderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderHistory',
        ),
    ]
