# Generated by Django 5.0.1 on 2024-04-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderplaced')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='product.addproduct')),
            ],
        ),
    ]
