# Generated by Django 5.0.1 on 2024-04-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_orderhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderhistory',
            new_name='orderhistoryDetails',
        ),
    ]
