# Generated by Django 5.0.1 on 2024-04-09 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_orderhistory_orderhistorydetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('feedbackDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('addProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.addproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
