# Generated by Django 5.0.1 on 2024-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_addproduct_isavailable_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='paymentType',
            field=models.CharField(default='online pay', max_length=100),
        ),
    ]
