# Generated by Django 5.0.1 on 2024-02-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDocument',
        ),
    ]
