# Generated by Django 5.0.1 on 2024-02-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_image/profiledefault.jpg', upload_to='profile_pics'),
        ),
    ]
