# Generated by Django 5.0.1 on 2024-02-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_staffdetails_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(default='customer', max_length=15),
        ),
    ]
