# Generated by Django 5.0.1 on 2024-02-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_service_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
