# Generated by Django 5.0.1 on 2024-03-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_servicedetail_staff_delete_bookappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
