# Generated by Django 5.0.1 on 2024-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_servicedetail_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
