# Generated by Django 5.0.1 on 2024-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userdetail_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='hasUserBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
