# Generated by Django 5.0.1 on 2024-03-01 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='BookDateTime',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='bookDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='bookTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
