# Generated by Django 5.0.1 on 2024-03-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_remove_bookappointment_bookdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
