# Generated by Django 5.0.1 on 2024-03-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_bookappointment_status_appointmentfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='status',
        ),
    ]
