# Generated by Django 5.0.1 on 2024-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_remove_bookappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
