# Generated by Django 5.0.1 on 2024-04-11 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0007_bookinglog_canceledappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfeedback',
            name='feedbackDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
