# Generated by Django 5.0.1 on 2024-04-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_appointmentfeedback_feedbackdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingLog',
        ),
    ]
